---
apiVersion: v1
kind: Secret
metadata:
  name: demo-db
type: Opaque
stringData:
  type: "postgresql"
  provider: "postgresql"
  host: "demo-db"
  port: "5432"          # container port
  database: "petclinic"
  username: "petclinic"
  password: "petclinic"

---
apiVersion: v1
kind: Service
metadata:
  name: demo-db
spec:
  selector:
    app: demo-db
  ports:
    - name: postgresql
      port: 7432           # service port (can map to host)
      targetPort: 5432     # container port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-db
  labels:
    app: demo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-db
  template:
    metadata:
      labels:
        app: demo-db
    spec:
      containers:
        - name: postgresql
          image: postgres:18.0
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: database
          ports:
            - containerPort: 5432
              name: postgresql
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
